### ISSUE TITLE
Protomsg: 여러 요소가 필요한 메시지

### ISSUE THREAD

**Issue by hyeunkim42** [42seoul-for-peer/ft_irc#10]
rpl_no 441, 443, 341이나 kick당했음을 알려주는 메시지들에는 인자가 다양하게 필요한데, 이런걸 어떻게 처리를 할지.

**Comment by eesum** [comment]
일단 지금 보면서 떠오르는 생각들 남겨놔요. 내일 이야기해봐요!

- 명령어마다 변주가 너무 다양해서, 각 명령어 함수 내에서 성공 or 실패에 따라 <Prefix> <Command> <args> :<msg> 의 <arg> 부분을 만들어서 멤버변수로 가지고 있기 (또는 args :<msg>를 한번에 가지고 있어도 될듯) -> 근데 결국 command 단위에서 응답은 더 쪼개져야 함

- 실제로 send할 단위로서 필요한 정보들을 모두 가진 Protocol 객체를 만들어서 서버에서는 걔만 쳐내기 -> 구조가 많이 바뀌긴 하지만 필요할지도...

**Comment by hyeunkim42** [comment]
다른 방법으로는 client 객체에 전송되어야 하는 msg를 prefix까지 포함시켜서 넣어놓는 방식도 있을 것 같아요. 문자열 형태로 계속 연장 가능하도록?
