### ISSUE TITLE
bug: JOIN 인자로 #없이 채널명을 보내면 Invalid channel name이 나와야 함

### ISSUE THREAD

**Issue by eesum** [42seoul-for-peer/ft_irc#11]
<img width="365" alt="image" src="https://github.com/user-attachments/assets/524c8e89-6f58-490f-8f66-977a20a7b00c">
현재는 No such channel 나오고 있음

**Comment by sj7288sj** [comment]
476 reply number가 RFC 1459에 존재하지 않아서 일단 no such channel 분기로 보내긴 했었습니다!
그래서 자체적으로 만들거나, RFC에 없는 number라 그냥 return만 해야하는지 얘기를 나눠봐야 할 것 같네요

**Comment by sj7288sj** [comment]
RFC1459의 reserved number로 존재하는 것을 확인해서 저희 임의로 문구를 구현하여 추가했고, 수정했습니다!
