### ISSUE TITLE
question: join 후 계속 join 하면 어떻게 될까요?

### ISSUE THREAD

**Issue by eesum** [42seoul-for-peer/ft_irc#24]
![image](https://github.com/user-attachments/assets/6abeace5-95cf-411a-87d6-64fdea8518a9)

**Comment by eesum** [comment]
<img width="404" alt="image" src="https://github.com/user-attachments/assets/2bb11dc6-b05c-4636-9a03-ff2c30b0cfe4">

개행만 빼면 될듯

**Comment by sj7288sj** [comment]
해결 완료!
