### ISSUE TITLE
question: MODE +l 인자에 숫자가 아닌 거 자꾸 넣으면 그냥 무시되는 건가요?

### ISSUE THREAD

**Issue by eesum** [42seoul-for-peer/ft_irc#25]
![image](https://github.com/user-attachments/assets/83c8ba4b-5201-4d8d-816a-45b41bf43d97)
뭔가 한번 이야기했던것도 같은데 기억이 가물 + 혹시나 해서 남겨놔용

**Comment by eesum** [comment]
![image](https://github.com/user-attachments/assets/80906d5f-ba7c-4aa4-b1f8-f329ad52b8ea)

**Comment by eesum** [comment]
<img width="347" alt="image" src="https://github.com/user-attachments/assets/67ec81f7-5846-4ee2-9763-f83d410f34db">
inspircd기준, atoi 하면서 0으로 변환되는듯

**Comment by sj7288sj** [comment]
수정해서 push했습니다!
