### ISSUE TITLE
question: mode 에 인자 제대로 안넣는 경우 아무 반응이 없는데 맞는걸까?

### ISSUE THREAD

**Issue by eesum** [42seoul-for-peer/ft_irc#26]
![image](https://github.com/user-attachments/assets/604f7ce9-fd92-4ae3-a601-b032b1e7f165)

**Comment by sj7288sj** [comment]
<img width="333" alt="image" src="https://github.com/user-attachments/assets/4ed0f7f4-6cf6-4a16-9140-d74affe89a1c">
통상 RFC 1459 환경에서는 MODE 이후 첫 인자에 '#'로 시작하는 채널 이름이 아닌 값이 들어올 경우 **nickname**을 받아온 것으로 간주합니다.
저희 ft_irc에서는 nickname option에 대해서 구현하지 않으므로,
RFC와 관련 없는 오류라고 판단해서 아무 것도 리턴하지 않도록 했습니다.
