### ISSUE TITLE
9/2 (Mon.): To do list

### ISSUE THREAD

**Issue by sj7288sj** [42seoul-for-peer/ft_irc#3]
- [x] USER -> seungjun
- [x] PING/PONG -> seungjun
- [x] PRIVMSG -> sumilee
- [x] 답장 만들기 -> hyeunkim
- [x] reply numbers header -> hyeunkim

**Comment by sj7288sj** [comment]
9/3 (Tue.): 에정

- signal handling
- JOIN
- CHANNEL commands
- etc.

**Comment by hyeunkim42** [comment]
ping의 경우 아무런 답장이나 가능하다는 정보를 얻어서, 우선은 안 만들고 진행하는걸로!

**Comment by sj7288sj** [comment]
확인~!
