### ISSUE TITLE
question: NICK 으로 닉네임 바꿀 시 채널 내 리스트, 초대 리스트 등에도 다 업데이트 되는가?

### ISSUE THREAD

**Issue by eesum** [42seoul-for-peer/ft_irc#32]

**Comment by sj7288sj** [comment]
<img width="362" alt="image" src="https://github.com/user-attachments/assets/7dcb964d-14c6-4e53-8a79-68977e5aa661">

channel list에서는 바뀌는 것 확인

<img width="362" alt="image" src="https://github.com/user-attachments/assets/1646bc4e-dece-4e8a-8edb-18aecd904db7">

invited list에서는 안바뀌네요 수정해보겠습니다.
