### ISSUE TITLE
bug: 비번 틀린 경우 에러메세지가 이상한 사람한테 간다..?

### ISSUE THREAD

**Issue by hyeunkim42** [42seoul-for-peer/ft_irc#35]
![image](https://github.com/user-attachments/assets/2356f6a3-7fb4-42fc-bca6-3f6f0de64394)
... pass는 오른쪽 client가 틀린건데, 종료는 왼쪽 client가 당함

왼쪽 nc의 fd가 더 작은 숫자라 먼저 찾아져서 그런듯... ㅠ

**Comment by eesum** [comment]
이거 해결하려면 결국 setMsgs 할때 첫번째 요소를 대상체 이름이 아니라 fd로 해야하는건가........?

**Comment by eesum** [comment]
https://github.com/42seoul-for-peer/ft_irc/commit/7c97e9eb534c2f1a5109587d70ff6e51e8134007
엣지케이스의 경우 send 시 clnt_fd를 파악하여 보내도록 변경함
