### ISSUE TITLE
bug: 이미 등록된 닉네임과 동일한 닉네임으로 NICK 보내고 USER 보내면 닉네임 없는 채로 welcome msg 받고 있음

### ISSUE THREAD

**Issue by eesum** [42seoul-for-peer/ft_irc#9]
<img width="950" alt="image" src="https://github.com/user-attachments/assets/dba2ba5b-5c23-48bc-82ea-4c56ed1a0c31">
왼쪽 터미널에서 먼저 dd 닉네임쓰고 오른쪽 터미널에서 dd 다시 썼는데 에러 메세지는 받았지만 register 과정은 여전히 유효한 상태.
USER 명령어를 마저 보내자 닉네임 부분이 빈채로 welcome msg 보내고 있음

**Comment by hyeunkim42** [comment]
지금은 해결되었습니다!
